create table if not exists public.typing_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mode text not null,
  wpm integer not null check (wpm >= 0),
  accuracy integer not null check (accuracy between 0 and 100),
  duration_seconds numeric(8,1) not null check (duration_seconds >= 0),
  typed_chars integer not null check (typed_chars >= 0),
  correct_chars integer not null check (correct_chars >= 0),
  mistakes integer not null check (mistakes >= 0),
  total_words integer not null check (total_words >= 0),
  completed_words integer not null check (completed_words >= 0),
  error_events jsonb not null default '[]'::jsonb,
  user_id uuid null references auth.users(id) on delete set null
);

alter table public.typing_runs enable row level security;

drop policy if exists "public can insert typing runs" on public.typing_runs;
create policy "public can insert typing runs"
  on public.typing_runs
  for insert
  with check (true);

drop policy if exists "public can read typing runs" on public.typing_runs;
create policy "public can read typing runs"
  on public.typing_runs
  for select
  using (true);
